version: 2
updates:
  - package-ecosystem: uv
    directory: /app
    open-pull-requests-limit: 0
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /app
    open-pull-requests-limit: 0
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directories:
      - /infra/bootstrap
      - /infra/envs/dev
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
